### ISSUE TITLE
C2 Infrastructure/Mechanism

### ISSUE THREAD

**Issue by NullArray** [sithis993/Crypter#14]
Out of interest. Will you be providing a C2 mechanism? As in, will you add capability to the ransomware to connect to a remote host where keys would be potentially stored? Be it deep web or otherwise.

**Comment by sithis993** [comment]
Yep absolutely. I just haven't gotten around to that component yet! I feel that adding this functionality does however go against my end goal, which is to be able to integrate the ransomware into the Botnet. In this case, there will be a Botnet command to deploy and somehow retrieve the key. Adding a C2 mechanism to the ransomware may get in the way when trying to achieve this goal. 

What I think I may do is create a separate branch on this repo which has this stuff, whilst the main master and develop branches do not.

There's one or two small issue I'd like to solve first, and then I think I will address this. I'm trying to learn Flask and I think the relatively simple CnC functionality required to perform this step will be a good way to get my teeth into it 👍 ;-)

**Comment by NullArray** [comment]
Awesome. Pretty excited to see the end result. In my case, i started to develop a C2 web app with Django, which i intend to finish eventually. However since i have a limited background in web development and since it was never intended to be in the project in the first place i kind of got side-tracked in the process. 

Like i said, cool project. Looking forward to the BETA.

**Comment by sithis993** [comment]
Ahh nice! I tried Django but I wasn't too keen on it. Flask seemed a little
more flexible and intuitive, though I probably didn't spend enough time
with Django.

If you've got any spare time feel free to contribute the webserver side ;-)
I suppose we'd only really need one page which would receive a POST request
containing a UUID and the AES key. It would then write that info to a
single table in a DB.

Nice and simple, for a first phase at least :-). I just haven't gotten
around to it yet. Currently in the process of addressing two things:

- Threading the decryption. Right now it isn't threaded and this causes the
program to block, which results in weird, though non-fatal, GUI glitches.
This is very nearly fixed.
- Coding the Builder.

After that, I'll happily take a look at this if it hasn't already been
addressed :-D

On 28 Jun 2017 9:20 pm, "NullArray" <notifications@github.com> wrote:

Awesome. Pretty excited to see the end result. In my case, i started to
develop a C2 web app with Django, which i intend to finish eventually.
However since i have a limited background in web development and since it
was never intended to be in the project in the first place i kind of got
side-tracked in the process.

Like i said, cool project. Looking forward to the BETA.

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sithis993/Crypter/issues/14#issuecomment-311777361>,
or mute
the thread

**Comment by NullArray** [comment]
I'll take a look at Flask. If i end up submitting a pull you will know, no promises though <3

**Comment by sithis993** [comment]
Haha! Feel free to use Django instead if you have a better understanding of
it :-) I don't really mind

On 28 Jun 2017 10:23 pm, "NullArray" <notifications@github.com> wrote:

I'll take a look at Flask. If i end up submitting a pull you will know, no
promises though <3

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/sithis993/Crypter/issues/14#issuecomment-311796288>,
or mute
the thread

**Comment by sithis993** [comment]
Issue closed due to changes in project direction (see README update)
