### ISSUE TITLE
Change title - request 

### ISSUE THREAD

**Issue by Dontmindmes** [sithis993/Crypter#48]
Possibility to change this?
https://gyazo.com/7e6bc359461943700576cc4254005831

**Comment by sithis993** [comment]
Yes, I've been meaning to do this for a little while and it's pretty easy :-). Will add an option into the Builder so you can specify the title. Should be able to get this done today. Will update this thread with my progress.

**Comment by sithis993** [comment]
Sorry this took longer than expected... It was quite simple but I struggled to find the time. Nevertheless it's now implemented and you can get this stuff in the latest release, or by pulling down the latest branch changes for either master or develop (it has been committed to both branches).

Closing this issue due to completion. Any problems please raise a new issue
