### ISSUE TITLE
What's the purpose of this project, besides creating destructive software?

### ISSUE THREAD

**Issue by TechnikEmpire** [sithis993/Crypter#49]
Your readme doesn't even claim education as a motive here, the purpose can be boiled down to "to prove that I can". Is this another case of some basement dwelling barely-capable virus developer publishing his work to github in order to land black market sales or what?

**Comment by sithis993** [comment]
Holy shit lol... and I was just about log off for the night XD. I feel like we should start a series for "Github developers read mean tweets". So far we have:

1. Basement dwelling
2. Barely Capable

But I know you can do better ;-)

**Comment by TechnikEmpire** [comment]
I'm asking if that's the case. I guess you didn't see the news about that dev who published his virus here because he was losing credit in the circle of scumbags and was losing sales. Anyway just asking if this is the case because you state no other reason than to prove yourself. Allow me to retract the ad hominem insinuations and focus on the question. What's the point?

**Comment by TechnikEmpire** [comment]
Did you test against current a/vs before publishing binaries of this to ensure that people were protected from malicious use? Did you submit it to a/vs for analysis who didn't catch it?  Did you consider either of those things? Feel like linking this to your identity? I'm gonna guess the answer to all of these questions is no.

**Comment by sithis993** [comment]
Shoot first, ask questions later. I like it ;-). My reasoning is the same reasoning that's been used throughout the life of computing: curiosity and interest in seeing what can be done. Quite simply I enjoy it, I think it's pretty interesting area and I haven't seen many others produce something like this in Python to the same level (this is probably the part where you belittle me from your throne high up in the clouds). 

My aim here is not to sell malware, or to distribute destructive software. You may not have noticed but this ransomware **does not** have a command and control component. The key is written to a local file so that the user can easily decrypt the files. There are plenty of other freely available malicious tools out there so I'm not exactly filling a void here with this. If somebody wants to then they can easily find the source for something like Zeus, which is fully functioning and distribute that. Plus as I'm "barely capable" I'm sure people could replicate it quite easily. 

Before I even published this repo I contacted GitHub to ask if it would break their T's and C's and they assured me it did not

Yes if you build it and submit it to the likes of VirusTotal then you should see that A/Vs will recognise the hash. It's also picked up by the likes of Microsoft Defender and such

**Comment by TechnikEmpire** [comment]
There's no cnc because by your own admission in other tickets you lack the ability to publish a good solution, yet you've gleefully solicited other developers who also admit they are inept to create a cnc for you.

Again, link to your identity. Nuff said on that point.

I'm not sitting up in the clouds I'm right here calling a spade a spade and suggesting that if you had legitimate interest in the science here you'd study mitigation. What you synthesize a flu variant then study how to kill it, that makes you a researcher. When you only study how to synthesize an alternative flu strain, publish the method and make no investigation into killing it, that makes you at worst a criminal and at least an incompetent person.

**Comment by sithis993** [comment]
This is truly brutal stuff! are you always this angry or am I receiving special treatment? In your experience, do you find that people are more receptive when you insult them? I usually find it to be counter-productive and I personally am a lot more open friendly suggestions and advice. Nevertheless I think we're starting to bond quite well... In truth, you had me at basement dweller ;-) When you do not know something, there is an opportunity to learn! 

I'm flattered you're spending your time on me and I can see some genuine concerns here, but I'm not really interested in your hostility, so to finalise:

Yes this was created for research and education purposes, but also because I find it interesting and enjoyable. If you have a problem then feel free to report the repository and I'll happily comply with any requests GitHub may have based upon your feedback.

**Comment by NullArray** [comment]
Simple, sophisticated, educational, destructive. It doesn't matter. People like TechnikEmpire ought not presume to have any sort of authority to tell people what they can and cannot do. The amount of arrogance is staggering.

**Comment by barney-the-greatest** [comment]
technikempire is a basic bitch.
