### ISSUE TITLE
Build process not creating key.txt

### ISSUE THREAD

**Issue by kingdomadmin** [sithis993/Crypter#56]
Hey sithis993,

Thanks for the project! I have been testing recently, however, I have run into a challenge with which I need some assistance. 

**Environment:**
-OS:  2 different Windows 10 Pro virtual machines
-Running crypter distributable 2.41
-All prerequisites installed in the order specified within the Readme file

I extracted the program on the first Windows 10 Pro machine to C:\tmp\Crypter_distributable_2.41 and successfully created the .exe and key.txt file. However, when attempting to duplicate the process subsequent times on the same machine or on the second Windows 10 Pro machine, it does not create the key.txt file.

Any thoughts? Thx.

**Comment by sithis993** [comment]
Hey! when you say it created the key.txt file, did you run the Builder to create the ransomware .exe and then run the .exe? It's the generated ransomware executable (crypter.exe) which produces the key.txt file, and not the Builder (Builder.pyw).

One other thing to note is that when Crypter runs for the first time and starts encrypting files, it will first generate an AES key and store it in key.txt. However, if there is already a key.txt file in the same directory as crypter.exe, it will use the AES key that's in this file rather than creating and using a new key.

Thanks!

**Comment by kingdomadmin** [comment]
Ahhhhh, that explains it then. I thought the build process created the key.txt. Just executed the .exe and the key.txt was created.

Thx for the clarity.

**Comment by sithis993** [comment]
Haha no problem ;-)
