### ISSUE TITLE
I would like to Support you with Donations

### ISSUE THREAD

**Issue by TechniChief** [sithis993/Crypter#60]
Hey I would really love to support you with Money to keep you still working on this Great Software. Tell me your Paypal.

**Comment by SecurityAnalysts** [comment]
Thank u kindly!https://paypal.me/YodaS5:36 AM, September 15, 2018, T3CH91CH13F <notifications@github.com>:Hey I would really love to support you with Money to keep you still working on this Great Software. Tell me your Paypal.

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sent from Yandex.Mail for mobile

**Comment by sithis993** [comment]
Hello many thanks but I don't think is a software project I can accept donations for :-)

**Comment by TechniChief** [comment]
You invested alot of time in this Great Software and You earned it.

**Comment by SecurityAnalysts** [comment]
Np ;)5:16 AM, September 15, 2018, Sithis <notifications@github.com>:Hello many thanks but I don't think is a software project I can accept donations for :-)

—You are receiving this because you commented.Reply to this email directly, view it on GitHub, or mute the thread.

-- Sent from Yandex.Mail for mobile

**Comment by sithis993** [comment]
Okay, well any support is really appreciated :-) my Paypal is paypal.me/sithis993

I do hope I can get back to this project at some point soon and add a few more features :-)
