### ISSUE TITLE
crypter is not encrypt

### ISSUE THREAD

**Issue by user568989** [sithis993/Crypter#61]
i tried to test this application on a real virus i created  a virus and tried to crypt it with this tool but when i uploaded it to virustotal

17 / 66 

i tried to make it FUD..

does the crypter work?
i saw the video and i dont see the red window , key.txt ,bin and some other files..
i downloaded the newest version..

**Comment by user568989** [comment]
problem solved i used version 1.3 but i am keep testing this great tool after 72 hours? the files decrypt auto? and they will no be more encrypted?

**Comment by sithis993** [comment]
Hi! After 72 hours the only thing that happens is you can no longer press the "Enter Decryption Key" button, as it will be disabled. The key isn't actually deleted. Also the timer is based upon a registry key value, so if you reaaaaaally need to get access to this button again, it is possible to change the registry key value (it's just an epoch time). The files do not auto-decrypt, you need to use the key to decrypt the files yourself manually.

With a real-world piece of ransomware, what would likely happen is the decryption fee would be increased, rather than the key being deleted. I just didn't get around to adding that functionality in

**Comment by user568989** [comment]
Thank you for your answer.. but i tried it out with a normal infected game made by me and when i encrypt it i could not open it i get an error:

Unsuppotree 16 bit application

cannot start or run due to incompatibility with 64-bit versions of Windows. Please contact the software vendor to ask if a 64-bit Windows compatible version is available


I think that's the error cause i am using my phone right now :)

**Comment by user568989** [comment]
Any idea how to make the file run?

**Comment by sithis993** [comment]
So you're encrypting a file (a game in this case), and then trying to run that file but you're hitting an error. Is that right? if you encrypt the file then you obviously wont be able to run it...
