### ISSUE TITLE
Builder issue

### ISSUE THREAD

**Issue by swagkarna** [sithis993/Crypter#74]
when i execute builder.pyw i got this error
Traceback (most recent call last):
  File "Builder.pyw", line 10, in <module>
    builder = Builder()
  File "C:\Users\xxx\Desktop\Crypter-master (3)\Crypter-master\CrypterBuilder\Builder.py", line 31, in
    self.__builder_gui = Gui()
  File "C:\Users\xxxx\Desktop\Crypter-master (3)\Crypter-master\CrypterBuilder\Gui.py", line 40, in __i
    MainFrame.__init__( self, parent=None )
  File "C:\Users\xxx\Desktop\Crypter-master (3)\Crypter-master\CrypterBuilder\BuilderGuiAbsBase.py", l
__
    bSizer44.Add( self.TitleLabel, 0, wx.ALIGN_CENTER_HORIZONTAL|wx.ALL|wx.EXPAND, 5 )
wx._core.wxAssertionError: C++ assertion "!(flags & (wxALIGN_RIGHT | wxALIGN_CENTRE_HORIZONTAL))" faile
mmon\sizer.cpp(2089) in wxBoxSizer::DoInsert(): Horizontal alignment flags are ignored with wxEXPAND

I am using windows 7 32 bit and python 3.7

**Comment by sithis993** [comment]
Huh, that's strange. Dud you install the dependencies using the requirements.txt file? (pip install -r requirements.txt). This looks like the kind of error that would occur if the version of wxPython wasn't correct. I haven't come across this problem with the Builder myself, so the version of wxPython I'm using (4.0.7) must be fine with this code

**Comment by swagkarna** [comment]
i am using python version 3.7 and i have installer all the requirements

**Comment by sithis993** [comment]
Hmmm this is quite strange. I've fixed this issue in the latest version of Crypter (3.4). Can you pull it down and give it a test? You shouldn't get this problem again, but you may get others.... it seems strange that you got this but other people haven't seen it. Sounds like there could be some other version of wxPython getting in the way.

Whenever I've seen wxPython errors like this, it's usually because a newer version no longer supports the use of certain flags, or perhaps is more lenient than an older version, etc. let me know how you get on :-)

**Comment by swagkarna** [comment]
Its working fine thanks
